import {
  PieChartOutlined,
  SettingOutlined,
  NotificationOutlined,
  AimOutlined,
  ToolOutlined,
  WarningOutlined,
  FormOutlined,
  SlidersOutlined,
  SmileOutlined,
  MessageOutlined,
  TeamOutlined,
  TagOutlined,
  GroupOutlined,
  CommentOutlined,
  ExceptionOutlined,
  BlockOutlined,
  FileTextOutlined,
  FilterOutlined,
  EyeOutlined,
  FileDoneOutlined,
  StockOutlined,
  DollarOutlined,
  InfoCircleOutlined,
  AudioMutedOutlined,
  StopOutlined,
  DeleteOutlined,
  ApiOutlined,
  UserOutlined,
  BugOutlined,
  DingtalkOutlined,
  LineChartOutlined,
  BarChartOutlined,
  RiseOutlined,
  EditOutlined,
} from '@ant-design/icons';

export const URL = 'http://46.101.203.185:3000/api/v1';

export const END_POINTS = {
  GROUPS: 'groups',
};

export const PANEL_MENU_ICONS = {
  settings: <SettingOutlined />,
  announcements: <NotificationOutlined />,
  privatebot: <PieChartOutlined />,
  channelrecords: <FormOutlined />,
  basicsettings: <ToolOutlined />,
  warning: <WarningOutlined />,
  principles: <FormOutlined />,
  advancedsettings: <SlidersOutlined />,
  welcome: <SmileOutlined />,
  message: <MessageOutlined />,
  newmembers: <TeamOutlined />,
  newmembersmentions: <TagOutlined />,
  general: <GroupOutlined />,
  systemmessages: <CommentOutlined />,
  blacklist: <ExceptionOutlined />,
  ratelimiter: <BlockOutlined />,
  additional: <FileTextOutlined />,
  commandfilter: <FilterOutlined />,
  advancedfilter: <EyeOutlined />,
  unfilteredmessages: <FilterOutlined />,
  reputation: <FileDoneOutlined />,
  levelsandxp: <StockOutlined />,
  crypto: <DollarOutlined />,
  warn: <InfoCircleOutlined />,
  muted: <AudioMutedOutlined />,
  block: <StopOutlined />,
  messagedelete: <DeleteOutlined />,
  triggersv2setting: <ApiOutlined />,
  'Yeni Üyeler': <UserOutlined />,
  'Anti Spam': <BugOutlined />,
  Filtreler: <FilterOutlined />,
  Eğlence: <DingtalkOutlined />,
  Raporlar: <LineChartOutlined />,
  stats: <BarChartOutlined />,
  users: <TeamOutlined />,
  rank: <RiseOutlined />,
  invite: <FormOutlined />,
  diary: <EditOutlined />,
};
